CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Developer" (
        "DeveloperId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Developer" PRIMARY KEY ("DeveloperId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "GameShop" (
        "ShopId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "BaseUrl" text,
        "ApiBaseUrl" text,
        CONSTRAINT "PK_GameShop" PRIMARY KEY ("ShopId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Genre" (
        "GenreId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Genre" PRIMARY KEY ("GenreId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Publisher" (
        "PublisherId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Publisher" PRIMARY KEY ("PublisherId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Role" (
        "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleName" text NOT NULL,
        CONSTRAINT "PK_Role" PRIMARY KEY ("RoleId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Game" (
        "GameId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text,
        "ReleaseDate" date,
        "DeveloperId" integer,
        "PublisherId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Game" PRIMARY KEY ("GameId"),
        CONSTRAINT "FK_Game_Developer_DeveloperId" FOREIGN KEY ("DeveloperId") REFERENCES "Developer" ("DeveloperId"),
        CONSTRAINT "FK_Game_Publisher_PublisherId" FOREIGN KEY ("PublisherId") REFERENCES "Publisher" ("PublisherId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "User" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLogin" timestamp with time zone,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_User" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_User_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("RoleId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "GameGenre" (
        "GameId" integer NOT NULL,
        "GenreId" integer NOT NULL,
        CONSTRAINT "PK_GameGenre" PRIMARY KEY ("GameId", "GenreId"),
        CONSTRAINT "FK_GameGenre_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
        CONSTRAINT "FK_GameGenre_Genre_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genre" ("GenreId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "GameOffer" (
        "GameOfferId" integer GENERATED BY DEFAULT AS IDENTITY,
        "GameId" integer NOT NULL,
        "ShopId" integer NOT NULL,
        "ExternalId" text,
        "DownloadUrl" text,
        "CurrentPrice" numeric NOT NULL,
        "CurrentDiscount" smallint NOT NULL,
        "Currency" text NOT NULL,
        "PriceSyncedAt" timestamp with time zone,
        CONSTRAINT "PK_GameOffer" PRIMARY KEY ("GameOfferId"),
        CONSTRAINT chk_discount CHECK ("CurrentDiscount" BETWEEN 0 AND 100),
        CONSTRAINT chk_price CHECK ("CurrentPrice" >= 0),
        CONSTRAINT "FK_GameOffer_GameShop_ShopId" FOREIGN KEY ("ShopId") REFERENCES "GameShop" ("ShopId") ON DELETE CASCADE,
        CONSTRAINT "FK_GameOffer_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "UserShopProfile" (
        "ProfileId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ShopId" integer NOT NULL,
        "ExternalUid" text NOT NULL,
        "LinkedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserShopProfile" PRIMARY KEY ("ProfileId"),
        CONSTRAINT "FK_UserShopProfile_GameShop_ShopId" FOREIGN KEY ("ShopId") REFERENCES "GameShop" ("ShopId") ON DELETE CASCADE,
        CONSTRAINT "FK_UserShopProfile_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "Wishlist" (
        "UserId" integer NOT NULL,
        "GameId" integer NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        "Source" text NOT NULL,
        CONSTRAINT "PK_Wishlist" PRIMARY KEY ("UserId", "GameId"),
        CONSTRAINT chk_source CHECK ("Source" IN ('manual', 'shop_import')),
        CONSTRAINT "FK_Wishlist_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
        CONSTRAINT "FK_Wishlist_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE TABLE "PriceHistory" (
        "PriceHistoryId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ListingId" integer NOT NULL,
        "RecordedAt" timestamp with time zone NOT NULL,
        "Price" numeric NOT NULL,
        "DiscountPercent" smallint NOT NULL,
        "Currency" text NOT NULL,
        "OfferGameOfferId" integer NOT NULL,
        CONSTRAINT "PK_PriceHistory" PRIMARY KEY ("PriceHistoryId"),
        CONSTRAINT "FK_PriceHistory_GameOffer_OfferGameOfferId" FOREIGN KEY ("OfferGameOfferId") REFERENCES "GameOffer" ("GameOfferId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    INSERT INTO "GameShop" ("ShopId", "ApiBaseUrl", "BaseUrl", "Name")
    VALUES (1, 'https://store.steampowered.com/api', 'https://store.steampowered.com', 'steam');
    INSERT INTO "GameShop" ("ShopId", "ApiBaseUrl", "BaseUrl", "Name")
    VALUES (2, 'https://api.gog.com', 'https://www.gog.com', 'gog');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    INSERT INTO "Role" ("RoleId", "RoleName")
    VALUES (1, 'admin');
    INSERT INTO "Role" ("RoleId", "RoleName")
    VALUES (2, 'moderator');
    INSERT INTO "Role" ("RoleId", "RoleName")
    VALUES (3, 'user');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_Game_DeveloperId" ON "Game" ("DeveloperId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_Game_PublisherId" ON "Game" ("PublisherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_GameGenre_GenreId" ON "GameGenre" ("GenreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GameOffer_GameId_ShopId" ON "GameOffer" ("GameId", "ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GameOffer_ShopId_ExternalId" ON "GameOffer" ("ShopId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_PriceHistory_ListingId_RecordedAt" ON "PriceHistory" ("ListingId", "RecordedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_PriceHistory_OfferGameOfferId" ON "PriceHistory" ("OfferGameOfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_User_RoleId" ON "User" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_UserShopProfile_ShopId" ON "UserShopProfile" ("ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserShopProfile_UserId_ShopId" ON "UserShopProfile" ("UserId", "ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    CREATE INDEX "IX_Wishlist_GameId" ON "Wishlist" ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"GameShop"', 'ShopId'),
        GREATEST(
            (SELECT MAX("ShopId") FROM "GameShop") + 1,
            nextval(pg_get_serial_sequence('"GameShop"', 'ShopId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Role"', 'RoleId'),
        GREATEST(
            (SELECT MAX("RoleId") FROM "Role") + 1,
            nextval(pg_get_serial_sequence('"Role"', 'RoleId'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406141436_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260406141436_InitialCreate', '8.0.25');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "PriceHistory" DROP CONSTRAINT "FK_PriceHistory_GameOffer_OfferGameOfferId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "Wishlist" DROP CONSTRAINT chk_source;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    DROP INDEX "IX_PriceHistory_ListingId_RecordedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    DROP INDEX "IX_PriceHistory_OfferGameOfferId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "Wishlist" DROP COLUMN "Source";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "PriceHistory" DROP COLUMN "ListingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "PriceHistory" RENAME COLUMN "OfferGameOfferId" TO "GameOfferId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "Wishlist" ADD "SourceShopId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE TABLE "Alert" (
        "AlertId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "GameId" integer NOT NULL,
        "TargetPrice" numeric,
        "TargetDiscount" smallint,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "TriggeredAt" timestamp with time zone,
        "LastNotifiedAt" timestamp with time zone,
        CONSTRAINT "PK_Alert" PRIMARY KEY ("AlertId"),
        CONSTRAINT chk_alert_condition CHECK ("TargetPrice" IS NOT NULL OR "TargetDiscount" IS NOT NULL),
        CONSTRAINT chk_alert_discount CHECK ("TargetDiscount" IS NULL OR ("TargetDiscount" BETWEEN 1 AND 100)),
        CONSTRAINT chk_alert_price CHECK ("TargetPrice" IS NULL OR "TargetPrice" > 0),
        CONSTRAINT "FK_Alert_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
        CONSTRAINT "FK_Alert_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE TABLE "UserLibrary" (
        "UserId" integer NOT NULL,
        "GameId" integer NOT NULL,
        "ShopId" integer NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserLibrary" PRIMARY KEY ("UserId", "GameId", "ShopId"),
        CONSTRAINT "FK_UserLibrary_GameShop_ShopId" FOREIGN KEY ("ShopId") REFERENCES "GameShop" ("ShopId") ON DELETE CASCADE,
        CONSTRAINT "FK_UserLibrary_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
        CONSTRAINT "FK_UserLibrary_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_Wishlist_SourceShopId" ON "Wishlist" ("SourceShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE UNIQUE INDEX "IX_User_Email" ON "User" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE UNIQUE INDEX "IX_User_Username" ON "User" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_PriceHistory_GameOfferId_RecordedAt" ON "PriceHistory" ("GameOfferId", "RecordedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE UNIQUE INDEX "IX_GameShop_Name" ON "GameShop" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_Game_Title" ON "Game" ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_Alert_GameId" ON "Alert" ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE UNIQUE INDEX "IX_Alert_UserId_GameId" ON "Alert" ("UserId", "GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_UserLibrary_GameId" ON "UserLibrary" ("GameId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    CREATE INDEX "IX_UserLibrary_ShopId" ON "UserLibrary" ("ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "PriceHistory" ADD CONSTRAINT "FK_PriceHistory_GameOffer_GameOfferId" FOREIGN KEY ("GameOfferId") REFERENCES "GameOffer" ("GameOfferId") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    ALTER TABLE "Wishlist" ADD CONSTRAINT "FK_Wishlist_GameShop_SourceShopId" FOREIGN KEY ("SourceShopId") REFERENCES "GameShop" ("ShopId") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE INDEX ix_alert_user_active
                        ON "Alert" ("UserId", "IsActive");
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE INDEX ix_alert_game_active
                        ON "Alert" ("GameId")
                        WHERE "IsActive" = TRUE AND "TriggeredAt" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE INDEX ix_user_library_user_added
                        ON "UserLibrary" ("UserId", "AddedAt" DESC);
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE INDEX ix_wishlist_source_shop
                        ON "Wishlist" ("SourceShopId")
                        WHERE "SourceShopId" IS NOT NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE INDEX ix_game_offer_synced_at
                        ON "GameOffer" ("PriceSyncedAt");
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_auto_price_history()
                        RETURNS TRIGGER
                        LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        IF (OLD."CurrentPrice" IS DISTINCT FROM NEW."CurrentPrice"
                            OR OLD."CurrentDiscount" IS DISTINCT FROM NEW."CurrentDiscount") THEN
                            INSERT INTO "PriceHistory" ("GameOfferId", "RecordedAt", "Price", "DiscountPercent", "Currency")
                            VALUES (OLD."GameOfferId", NOW(), OLD."CurrentPrice", OLD."CurrentDiscount", OLD."Currency");
                            NEW."PriceSyncedAt" = NOW();
                        END IF;
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE TRIGGER trg_auto_price_history
                        BEFORE UPDATE ON "GameOffer"
                        FOR EACH ROW
                        EXECUTE FUNCTION fn_auto_price_history();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_check_price_alerts()
                        RETURNS TRIGGER
                        LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        IF (NEW."CurrentPrice" = OLD."CurrentPrice"
                            AND NEW."CurrentDiscount" = OLD."CurrentDiscount") THEN
                            RETURN NEW;
                        END IF;

                        UPDATE "Alert"
                        SET "TriggeredAt" = NOW(),
                            "IsActive" = FALSE
                        WHERE "GameId" = NEW."GameId"
                          AND "IsActive" = TRUE
                          AND "TriggeredAt" IS NULL
                          AND (
                              ("TargetPrice" IS NOT NULL AND NEW."CurrentPrice" <= "TargetPrice")
                              OR
                              ("TargetDiscount" IS NOT NULL AND NEW."CurrentDiscount" >= "TargetDiscount")
                          );

                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE TRIGGER trg_check_price_alerts
                        AFTER UPDATE OF "CurrentPrice", "CurrentDiscount" ON "GameOffer"
                        FOR EACH ROW
                        EXECUTE FUNCTION fn_check_price_alerts();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_handle_library_insert()
                        RETURNS TRIGGER
                        LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        DELETE FROM "Wishlist"
                        WHERE "UserId" = NEW."UserId"
                          AND "GameId" = NEW."GameId";

                        UPDATE "Alert"
                        SET "IsActive" = FALSE
                        WHERE "UserId" = NEW."UserId"
                          AND "GameId" = NEW."GameId"
                          AND "IsActive" = TRUE;

                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE TRIGGER trg_handle_library_insert
                        AFTER INSERT ON "UserLibrary"
                        FOR EACH ROW
                        EXECUTE FUNCTION fn_handle_library_insert();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_update_game_timestamp()
                        RETURNS TRIGGER
                        LANGUAGE plpgsql
                    AS $$
                    BEGIN
                        NEW."UpdatedAt" = NOW();
                        RETURN NEW;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE TRIGGER trg_update_game_timestamp
                        BEFORE UPDATE ON "Game"
                        FOR EACH ROW
                        EXECUTE FUNCTION fn_update_game_timestamp();
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_get_user_alerts(p_user_id INT)
                        RETURNS TABLE (
                            alert_id        INT,
                            game_title      TEXT,
                            target_price    NUMERIC,
                            target_discount SMALLINT,
                            best_current_price    NUMERIC,
                            best_current_discount SMALLINT,
                            price_gap_pct   NUMERIC,
                            is_active       BOOLEAN,
                            triggered_at    TIMESTAMPTZ,
                            created_at      TIMESTAMPTZ
                        )
                        LANGUAGE sql
                        STABLE
                    AS $$
                        SELECT
                            a."AlertId",
                            g."Title",
                            a."TargetPrice",
                            a."TargetDiscount",
                            MIN(go."CurrentPrice"),
                            MAX(go."CurrentDiscount"),
                            CASE
                                WHEN a."TargetPrice" IS NOT NULL AND MIN(go."CurrentPrice") > 0
                                THEN ROUND(
                                    (MIN(go."CurrentPrice") - a."TargetPrice") / a."TargetPrice" * 100, 1)
                                ELSE NULL
                            END,
                            a."IsActive",
                            a."TriggeredAt",
                            a."CreatedAt"
                        FROM "Alert" a
                        JOIN "Game" g ON g."GameId" = a."GameId"
                        LEFT JOIN "GameOffer" go ON go."GameId" = a."GameId"
                        WHERE a."UserId" = p_user_id
                        GROUP BY a."AlertId", g."Title", a."TargetPrice", a."TargetDiscount",
                                 a."IsActive", a."TriggeredAt", a."CreatedAt"
                        ORDER BY a."IsActive" DESC, a."CreatedAt" DESC;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE FUNCTION fn_get_deal_score(p_game_offer_id INT)
                        RETURNS TABLE (
                            listing_id       INT,
                            shop_name        TEXT,
                            current_price    NUMERIC,
                            current_discount SMALLINT,
                            historical_low   NUMERIC,
                            historical_avg   NUMERIC,
                            deal_score       SMALLINT,
                            is_historical_low BOOLEAN
                        )
                        LANGUAGE sql
                        STABLE
                    AS $$
                        SELECT
                            go."GameOfferId",
                            gs."Name",
                            go."CurrentPrice",
                            go."CurrentDiscount",
                            COALESCE(MIN(ph."Price"), go."CurrentPrice"),
                            COALESCE(AVG(ph."Price"), go."CurrentPrice"),
                            CASE
                                WHEN COALESCE(MIN(ph."Price"), go."CurrentPrice") =
                                     COALESCE(MAX(ph."Price"), go."CurrentPrice")
                                THEN 0::SMALLINT
                                ELSE GREATEST(0, LEAST(100,
                                    ROUND(
                                        (1 - (go."CurrentPrice" - MIN(ph."Price")) /
                                             NULLIF(MAX(ph."Price") - MIN(ph."Price"), 0)
                                        ) * 100
                                    )::INT
                                ))::SMALLINT
                            END,
                            go."CurrentPrice" <= COALESCE(MIN(ph."Price"), go."CurrentPrice" + 1)
                        FROM "GameOffer" go
                        JOIN "GameShop" gs ON gs."ShopId" = go."ShopId"
                        LEFT JOIN "PriceHistory" ph ON ph."GameOfferId" = go."GameOfferId"
                        WHERE go."GameOfferId" = p_game_offer_id
                        GROUP BY go."GameOfferId", gs."Name", go."CurrentPrice", go."CurrentDiscount";
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE PROCEDURE pr_add_to_library(
                        p_user_id   INT,
                        p_game_id   INT,
                        p_shop_id   INT
                    )
                        LANGUAGE plpgsql
                    AS $$
                    DECLARE
                        v_game_title TEXT;
                        v_shop_name  TEXT;
                    BEGIN
                        SELECT "Title" INTO v_game_title
                        FROM "Game" WHERE "GameId" = p_game_id;
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Game with GameId=% not found', p_game_id;
                        END IF;

                        SELECT "Name" INTO v_shop_name
                        FROM "GameShop" WHERE "ShopId" = p_shop_id;
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Shop with ShopId=% not found', p_shop_id;
                        END IF;

                        INSERT INTO "UserLibrary" ("UserId", "GameId", "ShopId", "AddedAt")
                        VALUES (p_user_id, p_game_id, p_shop_id, NOW())
                        ON CONFLICT ("UserId", "GameId", "ShopId") DO NOTHING;

                        IF FOUND THEN
                            RAISE NOTICE 'Game added to library';
                        ELSE
                            RAISE NOTICE 'Game already in library';
                        END IF;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE PROCEDURE pr_set_alert(
                        p_user_id       INT,
                        p_game_id       INT,
                        p_target_price  NUMERIC DEFAULT NULL,
                        p_target_discount SMALLINT DEFAULT NULL
                    )
                        LANGUAGE plpgsql
                    AS $$
                    DECLARE
                        v_in_library BOOLEAN;
                    BEGIN
                        IF p_target_price IS NULL AND p_target_discount IS NULL THEN
                            RAISE EXCEPTION 'Must specify target_price or target_discount';
                        END IF;

                        SELECT EXISTS(
                            SELECT 1 FROM "UserLibrary"
                            WHERE "UserId" = p_user_id AND "GameId" = p_game_id
                        ) INTO v_in_library;

                        IF v_in_library THEN
                            RAISE EXCEPTION 'Game is already in your library — alert not needed';
                        END IF;

                        INSERT INTO "Alert"
                            ("UserId", "GameId", "TargetPrice", "TargetDiscount", "IsActive", "TriggeredAt", "CreatedAt")
                        VALUES
                            (p_user_id, p_game_id, p_target_price, p_target_discount, TRUE, NULL, NOW())
                        ON CONFLICT ON CONSTRAINT "IX_Alert_UserId_GameId"
                        DO UPDATE SET
                            "TargetPrice"    = EXCLUDED."TargetPrice",
                            "TargetDiscount" = EXCLUDED."TargetDiscount",
                            "IsActive"       = TRUE,
                            "TriggeredAt"    = NULL,
                            "CreatedAt"      = NOW();
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE VIEW vw_game_catalog AS
                    WITH genres_agg AS (
                        SELECT gg."GameId",
                               STRING_AGG(DISTINCT gn."Name", ', ' ORDER BY gn."Name") AS genres
                        FROM "GameGenre" gg
                        JOIN "Genre" gn ON gn."GenreId" = gg."GenreId"
                        GROUP BY gg."GameId"
                    ),
                    offers_agg AS (
                        SELECT go."GameId",
                               MIN(go."CurrentPrice") AS min_price,
                               MAX(go."CurrentDiscount") AS max_discount,
                               COUNT(DISTINCT go."ShopId") AS available_in_shops
                        FROM "GameOffer" go
                        GROUP BY go."GameId"
                    )
                    SELECT
                        g."GameId",
                        g."Title",
                        g."Description",
                        g."ReleaseDate",
                        d."Name" AS developer_name,
                        p."Name" AS publisher_name,
                        ga.genres,
                        oa.min_price,
                        oa.max_discount,
                        oa.available_in_shops,
                        g."CreatedAt",
                        g."UpdatedAt"
                    FROM "Game" g
                    LEFT JOIN "Developer" d ON d."DeveloperId" = g."DeveloperId"
                    LEFT JOIN "Publisher" p ON p."PublisherId" = g."PublisherId"
                    LEFT JOIN genres_agg ga ON ga."GameId" = g."GameId"
                    LEFT JOIN offers_agg oa ON oa."GameId" = g."GameId";
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN

                    CREATE OR REPLACE VIEW vw_user_library AS
                    SELECT
                        ul."UserId",
                        ul."GameId",
                        g."Title" AS game_title,
                        g."ReleaseDate",
                        d."Name" AS developer_name,
                        gs."Name" AS shop_name,
                        gs."BaseUrl" AS shop_url,
                        go."DownloadUrl",
                        go."CurrentPrice" AS purchase_store_price,
                        ul."AddedAt"
                    FROM "UserLibrary" ul
                    JOIN "Game" g ON g."GameId" = ul."GameId"
                    JOIN "GameShop" gs ON gs."ShopId" = ul."ShopId"
                    LEFT JOIN "Developer" d ON d."DeveloperId" = g."DeveloperId"
                    LEFT JOIN "GameOffer" go ON go."GameId" = ul."GameId"
                                              AND go."ShopId" = ul."ShopId";
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409131842_AddAlertsLibraryAndDbObjects') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260409131842_AddAlertsLibraryAndDbObjects', '8.0.25');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409133143_UpdateRoles') THEN
    UPDATE "Role" SET "RoleName" = 'guest'
    WHERE "RoleId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409133143_UpdateRoles') THEN
    UPDATE "Role" SET "RoleName" = 'user'
    WHERE "RoleId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409133143_UpdateRoles') THEN
    UPDATE "Role" SET "RoleName" = 'admin'
    WHERE "RoleId" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260409133143_UpdateRoles') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260409133143_UpdateRoles', '8.0.25');
    END IF;
END $EF$;
COMMIT;

