// <auto-generated />
using System;
using GameDB.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameDB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409182057_AddNormalizedTitleToGame")]
    partial class AddNormalizedTitleToGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameDB.Core.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("TargetDiscount")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AlertId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("Alert", null, t =>
                        {
                            t.HasCheckConstraint("chk_alert_condition", "\"TargetPrice\" IS NOT NULL OR \"TargetDiscount\" IS NOT NULL");

                            t.HasCheckConstraint("chk_alert_discount", "\"TargetDiscount\" IS NULL OR (\"TargetDiscount\" BETWEEN 1 AND 100)");

                            t.HasCheckConstraint("chk_alert_price", "\"TargetPrice\" IS NULL OR \"TargetPrice\" > 0");
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeveloperId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developer", (string)null);

                    b.HasData(
                        new
                        {
                            DeveloperId = 1,
                            Name = "Larian Studios"
                        },
                        new
                        {
                            DeveloperId = 2,
                            Name = "CD Projekt Red"
                        },
                        new
                        {
                            DeveloperId = 3,
                            Name = "FromSoftware"
                        },
                        new
                        {
                            DeveloperId = 4,
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            DeveloperId = 5,
                            Name = "Valve"
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("text");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("NormalizedTitle");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title");

                    b.ToTable("Game", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4153),
                            Description = "An epic RPG set in the D&D universe",
                            DeveloperId = 1,
                            PublisherId = 1,
                            ReleaseDate = new DateOnly(2023, 8, 3),
                            Title = "Baldur's Gate 3",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4154)
                        },
                        new
                        {
                            GameId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4160),
                            Description = "Open-world action RPG in a dystopian future",
                            DeveloperId = 2,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2020, 12, 10),
                            Title = "Cyberpunk 2077",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4161)
                        },
                        new
                        {
                            GameId = 3,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4166),
                            Description = "Open-world action RPG by FromSoftware and George R.R. Martin",
                            DeveloperId = 3,
                            PublisherId = 3,
                            ReleaseDate = new DateOnly(2022, 2, 25),
                            Title = "Elden Ring",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4167)
                        },
                        new
                        {
                            GameId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4172),
                            Description = "Roguelike action sequel from Supergiant Games",
                            DeveloperId = 4,
                            PublisherId = 4,
                            ReleaseDate = new DateOnly(2024, 5, 6),
                            Title = "Hades II",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4173)
                        },
                        new
                        {
                            GameId = 5,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4177),
                            Description = "Competitive tactical FPS",
                            DeveloperId = 5,
                            PublisherId = 5,
                            ReleaseDate = new DateOnly(2023, 9, 27),
                            Title = "Counter-Strike 2",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4178)
                        },
                        new
                        {
                            GameId = 6,
                            CreatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4182),
                            Description = "Story-driven open world RPG",
                            DeveloperId = 2,
                            PublisherId = 2,
                            ReleaseDate = new DateOnly(2015, 5, 19),
                            Title = "The Witcher 3: Wild Hunt",
                            UpdatedAt = new DateTime(2026, 4, 9, 18, 20, 56, 775, DateTimeKind.Utc).AddTicks(4183)
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenre", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.GameOffer", b =>
                {
                    b.Property<int>("GameOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameOfferId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("CurrentDiscount")
                        .HasColumnType("smallint");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PriceSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("GameOfferId");

                    b.HasIndex("GameId", "ShopId")
                        .IsUnique();

                    b.HasIndex("ShopId", "ExternalId")
                        .IsUnique();

                    b.ToTable("GameOffer", null, t =>
                        {
                            t.HasCheckConstraint("chk_discount", "\"CurrentDiscount\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("chk_price", "\"CurrentPrice\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            GameOfferId = 1,
                            Currency = "USD",
                            CurrentDiscount = (short)0,
                            CurrentPrice = 59.99m,
                            ExternalId = "1086940",
                            GameId = 1,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 2,
                            Currency = "USD",
                            CurrentDiscount = (short)0,
                            CurrentPrice = 59.99m,
                            ExternalId = "1086940",
                            GameId = 1,
                            ShopId = 2
                        },
                        new
                        {
                            GameOfferId = 3,
                            Currency = "USD",
                            CurrentDiscount = (short)50,
                            CurrentPrice = 29.99m,
                            ExternalId = "1091500",
                            GameId = 2,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 4,
                            Currency = "USD",
                            CurrentDiscount = (short)50,
                            CurrentPrice = 29.99m,
                            ExternalId = "1423049",
                            GameId = 2,
                            ShopId = 2
                        },
                        new
                        {
                            GameOfferId = 5,
                            Currency = "USD",
                            CurrentDiscount = (short)0,
                            CurrentPrice = 59.99m,
                            ExternalId = "1245620",
                            GameId = 3,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 6,
                            Currency = "USD",
                            CurrentDiscount = (short)0,
                            CurrentPrice = 29.99m,
                            ExternalId = "1145350",
                            GameId = 4,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 7,
                            Currency = "USD",
                            CurrentDiscount = (short)0,
                            CurrentPrice = 0.00m,
                            ExternalId = "730",
                            GameId = 5,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 8,
                            Currency = "USD",
                            CurrentDiscount = (short)75,
                            CurrentPrice = 9.99m,
                            ExternalId = "292030",
                            GameId = 6,
                            ShopId = 1
                        },
                        new
                        {
                            GameOfferId = 9,
                            Currency = "USD",
                            CurrentDiscount = (short)75,
                            CurrentPrice = 9.99m,
                            ExternalId = "1495134320",
                            GameId = 6,
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.GameShop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopId"));

                    b.Property<string>("ApiBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShopId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameShop", (string)null);

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            ApiBaseUrl = "https://store.steampowered.com/api",
                            BaseUrl = "https://store.steampowered.com",
                            Name = "Steam"
                        },
                        new
                        {
                            ShopId = 2,
                            ApiBaseUrl = "https://api.gog.com",
                            BaseUrl = "https://www.gog.com",
                            Name = "GOG"
                        },
                        new
                        {
                            ShopId = 3,
                            ApiBaseUrl = "https://store.epicgames.com/graphql",
                            BaseUrl = "https://store.epicgames.com",
                            Name = "Epic Games Store"
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Roguelike"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Open World"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "FPS"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Indie"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.ImportJob", b =>
                {
                    b.Property<int>("ImportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportJobId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("text");

                    b.Property<int>("EgsImported")
                        .HasColumnType("integer");

                    b.Property<int>("EgsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("EgsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("GogImported")
                        .HasColumnType("integer");

                    b.Property<int>("GogProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("GogTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SteamImported")
                        .HasColumnType("integer");

                    b.Property<int>("SteamProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("SteamTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGamesCreated")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOffersCreated")
                        .HasColumnType("integer");

                    b.HasKey("ImportJobId");

                    b.ToTable("ImportJob", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.PriceHistory", b =>
                {
                    b.Property<int>("PriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceHistoryId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("DiscountPercent")
                        .HasColumnType("smallint");

                    b.Property<int>("GameOfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("GameOfferId", "RecordedAt");

                    b.ToTable("PriceHistory", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublisherId");

                    b.ToTable("Publisher", (string)null);

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            Name = "Larian Studios"
                        },
                        new
                        {
                            PublisherId = 2,
                            Name = "CD Projekt"
                        },
                        new
                        {
                            PublisherId = 3,
                            Name = "Bandai Namco"
                        },
                        new
                        {
                            PublisherId = 4,
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            PublisherId = 5,
                            Name = "Valve"
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "guest"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "user"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "admin"
                        });
                });

            modelBuilder.Entity("GameDB.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.UserLibrary", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GameId", "ShopId");

                    b.HasIndex("GameId");

                    b.HasIndex("ShopId");

                    b.ToTable("UserLibrary", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.UserShopProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("ExternalUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId", "ShopId")
                        .IsUnique();

                    b.ToTable("UserShopProfile", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.Wishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SourceShopId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.HasIndex("SourceShopId");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("GameDB.Core.Models.Alert", b =>
                {
                    b.HasOne("GameDB.Core.Models.Game", "Game")
                        .WithMany("Alerts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Core.Models.Game", b =>
                {
                    b.HasOne("GameDB.Core.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("GameDB.Core.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameDB.Core.Models.GameGenre", b =>
                {
                    b.HasOne("GameDB.Core.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameDB.Core.Models.GameOffer", b =>
                {
                    b.HasOne("GameDB.Core.Models.Game", "Game")
                        .WithMany("Offers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.GameShop", "Shop")
                        .WithMany("Offers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("GameDB.Core.Models.PriceHistory", b =>
                {
                    b.HasOne("GameDB.Core.Models.GameOffer", "Offer")
                        .WithMany("PriceHistories")
                        .HasForeignKey("GameOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("GameDB.Core.Models.User", b =>
                {
                    b.HasOne("GameDB.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GameDB.Core.Models.UserLibrary", b =>
                {
                    b.HasOne("GameDB.Core.Models.Game", "Game")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.GameShop", "Shop")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.User", "User")
                        .WithMany("Library")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Core.Models.UserShopProfile", b =>
                {
                    b.HasOne("GameDB.Core.Models.GameShop", "Shop")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.User", "User")
                        .WithMany("ShopProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Core.Models.Wishlist", b =>
                {
                    b.HasOne("GameDB.Core.Models.Game", "Game")
                        .WithMany("Wishlists")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Core.Models.GameShop", "SourceShop")
                        .WithMany()
                        .HasForeignKey("SourceShopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameDB.Core.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SourceShop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Core.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameDB.Core.Models.Game", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("GameGenres");

                    b.Navigation("LibraryEntries");

                    b.Navigation("Offers");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("GameDB.Core.Models.GameOffer", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("GameDB.Core.Models.GameShop", b =>
                {
                    b.Navigation("LibraryEntries");

                    b.Navigation("Offers");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("GameDB.Core.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("GameDB.Core.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameDB.Core.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GameDB.Core.Models.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Library");

                    b.Navigation("ShopProfiles");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
